linkPrefix = ''
#linkPrefix = '/numenta-web'  # integration/staging (gh-pages)

baseUrl = 'https://numenta.com'
#baseUrl = 'http://staging.numenta.com'

siteHost = 'Numenta.com'
siteTitle = ''
description = 'Leading the New Era of Machine Intelligence'
company = 'Numenta'
logo = "/assets/img/logo.png"
[contact]
  [contact.email]
    feedback = 'feedback@numenta.com'
    info = 'info@numenta.com'
    press = 'press@numenta.com'
    sales = 'sales@numenta.com'
    licenses = 'licenses@numenta.com'
    support = 'support@numenta.com'
  [contact.phone]
    fax = '650-369-8283'
    tel = '650-369-8282'

[analytics]
  google = 'UA-48460134-1'
  pingdom = '569029d1abe53daf465fa724'

[links]
  [links.out]  # external links
    # apps
    apps = 'https://github.com/numenta/numenta-apps'
    grokGet = 'http://grokstream.com/#pricing'
    geo = 'https://github.com/numenta/nupic.geospatial'
    rogue = 'https://github.com/numenta/nupic.rogue'
    # legal
    patents = 'http://patft.uspto.gov/netacgi/nph-Parser?Sect1=PTO2&Sect2=HITOFF&p=1&u=%2Fnetahtml%2FPTO%2Fsearch-bool.html&r=0&f=S&l=50&TERM1=Numenta&FIELD1=ASNM&co1=AND&TERM2=&FIELD2=&d=PTXT'
    trial = 'http://numenta.org/licenses/trial/'
    # partners
    cortical = 'http://cortical.io'
    grok = 'http://grokstream.com'
    # Org
    org = 'http://numenta.org'
    # social
    facebook = 'https://www.facebook.com/OfficialNumenta'
    linkedin = 'https://www.linkedin.com/company/numenta'
    map = 'http://maps.google.com/maps?q=791+Middlefield+Road,+Redwood+City,+CA+94063'
    twitter = 'https://twitter.com/numenta'
    # YouTube
    [links.out.htmschool]
      channel = 'https://www.youtube.com/OfficialNumenta'
      sptalk = 'https://www.youtube.com/watch?v=1r6GxDsEdd0'
      episode7 = 'https://www.youtube.com/watch?v=R5UoFNtv5AU'
      episode8 = 'https://www.youtube.com/watch?v=rHvjykCIrZM'
      episode9 = 'https://www.youtube.com/watch?v=MSwoNAODrgk'


  [links.in]  # internal paths
    # main/home pseudo-single page
    home = '/'
    nutshell = '/machine-intelligence-technology/numenta-in-a-nutshell/'
    mission = '/company/mission-and-history/'
    neuro = '/machine-intelligence-technology/neuroscience-research/'
    technology = '/machine-intelligence-technology/'
    opensource = '/resources/open-source-community/'
    applications = '/applications/'
    partners = '/partners/'
    business = '/machine-intelligence-technology/business-strategy-and-ip/'
    anomaly = '/applications/anomaly-detection-benchmark/'
    resources = '/resources/papers-videos-and-more/'
    careers = '/company/careers-and-team/'
    visitingscholar = '/company/careers-and-team/careers/visiting-scholar-program/'
    contact = '/contact/'
    # other site pages
    bami = '/resources/biological-and-machine-intelligence/'
    spweb = '/resources/biological-and-machine-intelligence/spatial-pooling-algorithm/'
    sppdf = '/assets/pdf/spatial-pooling-algorithm/Spatial-Pooling-Algorithm-Details.pdf'
    tm = '/resources/biological-and-machine-intelligence/temporal-memory-algorithm/'
    blog = '/blog/'
    events = '/company/events/'
    htmstudio = '/applications/htm-studio/'
    nab = '/applications/numenta-anomaly-benchmark/'
    newsletter = '/company/newsletter/'
    papers = '/resources/papers/'
    sppaper = '/resources/papers/htm-spatial-pooler-neocortical-algorithm-for-online-sparse-distributed-coding/'
    papersvideos = '/resources/papers-videos-and-more/'
    press = '/press/'
    pressreleases = '/press/releases/'
    presslinks = '/press/links/'
    privacy = '/legal/privacy/'
    sitemap = '/sitemap/'
    terms = '/legal/terms/'
    license = '/assets/pdf/apps/licensing-guide.pdf'
    htmforstocks = '/assets/pdf/apps/htmforstocks.pdf'
    [links.in.slides]
      sptalk = '/assets/pdf/spatial-pooling-algorithm/HTM-Spatial-Pooler-Overview.pdf'

[moments]
  post = 'YYYY/MM/DD'
  human = 'ddd, MMM DD, YYYY'
